### ISSUE TITLE
Error code running blinReg

### ISSUE THREAD

**Issue by kaileylanger** [jonathon-love/jsq#6]
Hi, thank you for providing this code it is very helpful! I have used the blinReg function successfully in the past week, but I recently updated my dataset and when I made corresponding changes to the code (really just switching variable names) I started getting an error that I do not understand. 

Error is as follows:
Error in eval(predvars, data, env) : 
  object 'XWnBhaW5fc3VtX2xvY2F0aW9u' not found

That object is not one that I have anywhere in my code or in my dataset, I was hoping you may be able to help me identify where that is coming from. 

Thanks!
Kailey

**Comment by jonathon-love** [comment]
hi kailey,

let me show you a clever trick :)

a number of R packages don't cope with variables which have spaces in them, so we often need to resort to using "base64 encoding". so if you decode that string with a website like this one:

https://www.base64decode.org/

oh, but there's one more trick ... because sometimes the base64 string starts with numbers, R barfs on it, so we add an additional `X` to the front to prevent this problem. so let's drop off the `X`, and decode `WnBhaW5fc3VtX2xvY2F0aW9u`, and we end up with:

```
Zpain_sum_location
```

cheers

**Comment by kaileylanger** [comment]
Holy wow! Thank you so so much!

**Comment by jonathon-love** [comment]
my pleasure! sorry the error messages aren't more helpful!

jonathon
